### ISSUE TITLE
SerializingTranscoder problem

### ISSUE THREAD

**Issue by cmw** [mje113/couchbase-jruby-client#12]
When trying to use couchbase-jruby-client on a strom cluster - deployed with redstorm - I get

    org.jruby.exceptions.RaiseException: (ArgumentError) unable to create proxy class for class net.spy.memcached.transcoders.SerializingTranscoder

Running it locally works without a problem, though. I even tried making the dependency explicit by adding it to the ivy config file, but that didn't have any effect - and the jar file from the lib directory was already present on the server anyway.

Any ideas/pointers?

**Comment by mje113** [comment]
hmm... this repo is somewhat unmaintained. I'm planning to prepare a release to support the 2.0 JDK SDK version but I'm not sure how soon that will happen.
